const translations: Record<string, string> = {
    "Goal Disallowed - offside": "Gol annullato - Fuorigioco",
    "Yellow Card": "Cartellino giallo",
    "Red Card": "Cartellino rosso",
    "Substitution": "Sostituzione",
    "Tripping": "Sgambetto",
    "Delay of game": "Rallentamento del gioco",
    "Foul": "Fallo",
    "Serious foul": "Brutto Fallo",
    "Roughing": "Eccesso di Foga",
    "Goal confirmed": "Gol Confermato",
    "Penalty": "Rigore",
    "Shots on Goal": "Tiri in Porta",
    "Shots off Goal": "Tiri Fuori",
    "Total Shots": "Tiri Totali",
    "Blocked Shots": "Tiri bloccati",
    "Shots insidebox": "Tiri da Dentro Area",
    "Shots outsidebox": "Tiri da Fuori Area",
    "Fouls": "Falli",
    "Corner Kicks": "Calci D'Angolo",
    "Offsides": "Fuorigioco",
    "Ball Possession": "Possesso Palla",
    "Yellow Cards": "Cartellino Giallo",
    "Red Cards": "Cartellino Rosso",
    "Goalkeeper Saves": "Parate del Portiere",
    "Total passes": "Passaggi Totali",
    "Passes accurate": "Passaggi Completati",
    "Passes %": "Percentuale Passaggi",
    "expected_goals": "xG",
    "goals_prevented": "xNG",
    "Match Winner": "Vincitore Partita",
    "First Half Winner": "Vincitore Primo Tempo",
    "Second Half Winner": "Vincitore Secondo Tempo",
    "Goals Over/Under First Half": "Gol Over/Under Primo Tempo",
    "Goals Over/Under - Second Half": "Gol Over/Under Secondo Tempo",
    "HT/FT Double": "1T / 2T",
    "Clean Sheet - Home": "Porta Inviolata - Casa",
    "Clean Sheet - Away": "Porta Inviolata - Ospite",
    "Both Teams Score": "Goal Goal",
    "Handicap Result": "Risultato Handicap",
    "Exact Score": "Risultato Esatto",
    "Correct Score - First Half": "Risultato Corretto - Primo Tempo",
    "Correct Score - Second Half": "Risultato Corretto - Secondo Tempo",
    "Double Chance": "Doppia Chance",
    "Home/Draw": "1X",
    "Draw/Away": "X2",
    "Home/Away": "12",
    "Draw/Draw": "X / X",
    "Home/Home": "1 / 1",
    
    "Team To Score First": "Prima Squadra a Segnare",
    "Team To Score Last": "Ultima Squadra a Segnare",
    "Total - Home": "Totale - Casa",
    "Total - Away": "Totale - Ospite",
    "Double Chance - First Half": "Doppia Chance - Primo Tempo",
    "Double Chance - Second Half": "Doppia Chance - Secondo Tempo",
    "Both Teams Score - First Half": "Goal Goal - Primo Tempo",
    "Both Teams Score - Second Half": "Goal Goal - Secondo Tempo",
    "Odd/Even": "Pari/Dispari",
    "Exact Goals Number": "Somma Goals",
    "To Win Either Half": "Vince Entrambi i Tempi",
    "Results/Both Teams Score": "Risultato/Goal Goal",
    "Result/Total Goals": "Risultato/Over-Under",
    "Own Goal": "AutoGoal",
    "Anytime Goal Scorer": "Marcatore",
    "First Goal Scorer": "Primo Marcatore",
    "Last Goal Scorer": "Ultimo Marcatore",
    "Player Assists": "Assist",
  };
  
  export function translate(text: string): string {
    return translations[text] ?? text; 
  }