const translations: Record<string, string> = {
    "Goal Disallowed - offside": "Gol annullato - Fuorigioco",
    "Yellow Card": "Cartellino giallo",
    "Red Card": "Cartellino rosso",
    "Substitution": "Sostituzione",
    "Tripping": "Sgambetto",
    "Delay of game": "Rallentamento del gioco",
    "Foul": "Fallo",
    "Serious foul": "Brutto Fallo",
    "Roughing": "Eccesso di Foga",
    "Goal confirmed": "Gol Confermato",
    "Penalty": "Rigore",
    "Shots on Goal": "Tiri in Porta",
    "Shots off Goal": "Tiri Fuori",
    "Total Shots": "Tiri Totali",
    "Blocked Shots": "Tiri bloccati",
    "Shots insidebox": "Tiri da Dentro Area",
    "Shots outsidebox": "Tiri da Fuori Area",
    "Fouls": "Falli",
    "Corner Kicks": "Calci D'Angolo",
    "Offsides": "Fuorigioco",
    "Ball Possession": "Possesso Palla",
    "Yellow Cards": "Cartellino Giallo",
    "Red Cards": "Cartellino Rosso",
    "Goalkeeper Saves": "Parate del Portiere",
    "Total passes": "Passaggi Totali",
    "Passes accurate": "Passaggi Completati",
    "Passes %": "Percentuale Passaggi",
    "expected_goals": "xG",
    "goals_prevented": "xNG",
    "Match Winner": "Vincitore",
    "First Half Winner": "Vincitore Primo Tempo",
    "Second Half Winner": "Vincitore 2° Tempo",
    "Goals Over/Under": "Goals Over / Under",
    "Goals Over/Under First Half": "Goals Over/Under 1° Tempo",
    "Goals Over/Under - Second Half": "Goals Over/Under 2° Tempo",
    "HT/FT Double": "1° TEMPO / 2° TEMPO",
    "Clean Sheet - Home": "Porta Inviolata - Casa",
    "Clean Sheet - Away": "Porta Inviolata - Ospite",
    "Both Teams Score": "Goal Goal",
    "Handicap Result": "Risultato Handicap",
    "Exact Score": "Risultato Esatto",
    "Correct Score - First Half": "Risultato Corretto - Primo Tempo",
    "Correct Score - Second Half": "Risultato Corretto - Secondo Tempo",
    "Double Chance": "Doppia Chance",
    "Home/Draw": "1X",
    "Draw/Away": "X2",
    "Home/Away": "12",
    "Draw/Draw": "X / X",
    "Home/Home": "1 / 1",
    "Team To Score First": "Prima Squadra a Segnare",
    "Team To Score Last": "Ultima Squadra a Segnare",
    "Total - Home": "Totale - Casa",
    "Total - Away": "Totale - Ospite",
    "Double Chance - First Half": "Doppia Chance - Primo Tempo",
    "Double Chance - Second Half": "Doppia Chance - Secondo Tempo",
    "Both Teams Score - First Half": "Goal Goal - Primo Tempo",
    "Both Teams Score - Second Half": "Goal Goal - Secondo Tempo",
    "Odd/Even": "Pari / Dispari",
    "Exact Goals Number": "Somma Goals",
    "To Win Either Half": "Vince Entrambi i Tempi",
    "Results/Both Teams Score": "Risultato/Goal Goal",
    "Result/Total Goals": "Risultato/Over-Under",
    "Own Goal": "AutoGoal",
    "Anytime Goal Scorer": "Marcatore",
    "First Goal Scorer": "Primo Marcatore",
    "Last Goal Scorer": "Ultimo Marcatore",
    "Player Assists": "Assist",
    "Yes": "Si",
    "No": "No",
    "Highest Scoring Half": "Miglior Tempo per Goals",
    "1st Half": "Primo Tempo",
    "2nd Half": "Secondo Tempo",
    "Home": "1",
    "Away": "2",
    "Draw": "X",
    "Odd": "Dispari",
    "Even": "Pari",
    "Odd/Even - First Half": "Pari / Dispari - Primo Tempo",
    "Home Odd/Even": "Pari / Dispari - Casa",
    "Away Odd/Even": "Pari / Dispari - Ospite",
    "Home Team Exact Goals Number": "Somma Goals - Casa",
    "Away Team Exact Goals Number": "Somma Goals - Ospite",
    "Second Half Exact Goals Number": "Somma Goals - Secondo Tempo",
    "more 3": "3+",
    "Home/Yes": "1 / SI",
    "Away/Yes": "2 / SI",
    "Draw/Yes": "X / SI",
    "Home/No": "1 / NO",
    "Away/No": "2 / NO",
    "Draw/No": "X / NO",
    "1 by 1": "1 - 1 Goal",
    "1 by 2": "1 - 2 Goals",
    "1 by 3": "1 - 3 Goals",
    "1 by 4+": "1 - 4+ Goals",
    "Score Draw": "Uguali Goals",
    "2 by 1": "2 - 1 Goal",
    "2 by 2": "2 - 2 Goals",
    "2 by 3": "2 - 3 Goals",
    "2 by 4+": "2 - 4+ Goals",
    "Winning Margin": "Scarto Vittoria",
    "Total Goals/Both Teams To Score": "Over-Under / Goal Goal",
    "o/yes 2.5": "OVER 2.5 / SI",
    "o/no 2.5": "OVER 2.5 / NO",
    "u/yes 2.5": "UNDER 2.5 / SI",
    "u/no 2.5": "UNDER 2.5 / NO",
    "Home/Over 2.5": "1 / OVER 2.5",
    "Away/Over 2.5": "2 / OVER 2.5",
    "Draw/Over 2.5": "X / OVER 2.5",
    "Home/Under 2.5": "1 / UNDER 2.5",
    "Away/Under 2.5": "2 / UNDER 2.5",
    "Draw/Under 2.5": "X / UNDER 2.5",
    "more 7": "7+",
  };
  
  export function translate(text: string): string {
    return translations[text] ?? text; 
  }