const translations: Record<string, string> = {
  "Goal Disallowed - offside": "Gol annullato - Fuorigioco",
  "Yellow Card": "Cartellino giallo",
  "Red Card": "Cartellino rosso",
  "Substitution": "Sostituzione",
  "Tripping": "Sgambetto",
  "Delay of game": "Rallentamento del gioco",
  "Foul": "Fallo",
  "Serious foul": "Brutto Fallo",
  "Roughing": "Eccesso di Foga",
  "Goal confirmed": "Gol Confermato",
  "Penalty": "Rigore",
  "Shots on Goal": "Tiri in Porta",
  "Shots off Goal": "Tiri Fuori",
  "Total Shots": "Tiri Totali",
  "Blocked Shots": "Tiri bloccati",
  "Shots insidebox": "Tiri da Dentro Area",
  "Shots outsidebox": "Tiri da Fuori Area",
  "Fouls": "Falli",
  "Corner Kicks": "Calci D'Angolo",
  "Offsides": "Fuorigioco",
  "Ball Possession": "Possesso Palla",
  "Yellow Cards": "Cartellino Giallo",
  "Red Cards": "Cartellino Rosso",
  "Goalkeeper Saves": "Parate del Portiere",
  "Total passes": "Passaggi Totali",
  "Passes accurate": "Passaggi Completati",
  "Passes %": "Percentuale Passaggi",
  "expected_goals": "xG",
  "goals_prevented": "xNG",
  "Match Winner": "Vincitore",
  "First Half Winner": "Vincitore 1° Tempo",
  "Second Half Winner": "Vincitore 2° Tempo",
  "Goals Over/Under": "Over / Under",
  "Goals Over/Under First Half": "Over/Under 1° Tempo",
  "Goals Over/Under - Second Half": "Over/Under 2° Tempo",
  "HT/FT Double": "1° TEMPO / 2° TEMPO",
  "Clean Sheet - Home": "Porta Inviolata - Casa",
  "Clean Sheet - Away": "Porta Inviolata - Ospite",
  "Both Teams Score": "Goal Goal",
  "Handicap Result": "Risultato Handicap",
  "Exact Score": "Risultato Esatto",
  "Correct Score - First Half": "Risultato Corretto - 1° Tempo",
  "Correct Score - Second Half": "Risultato Corretto - 2° Tempo",
  "Double Chance": "Doppia Chance",
  "Home/Draw": "1X",
  "Draw/Away": "X2",
  "Home/Away": "12",
  "Draw/Draw": "X / X",
  "Home/Home": "1 / 1",
  "Team To Score First": "Prima Squadra a Segnare",
  "Team To Score Last": "Ultima Squadra a Segnare",
  "Total - Home": "Over / Under - Casa",
  "Total - Away": "Over / Under - Ospite",
  "Double Chance - First Half": "Doppia Chance - 1° Tempo",
  "Double Chance - Second Half": "Doppia Chance - 2° Tempo",
  "Both Teams Score - First Half": "Goal Goal - 1° Tempo",
  "Both Teams To Score - Second Half": "Goal Goal - 2° Tempo",
  "Odd/Even": "Pari / Dispari",
  "Exact Goals Number": "Somma Goals",
  "Exact Goals Number - First Half": "Somma Goals - 1° Tempo",
  "To Win Either Half": "Vince Entrambi i Tempi",
  "Results/Both Teams Score": "Risultato/Goal Goal",
  "Result/Total Goals": "Risultato/Over-Under",
  "Own Goal": "AutoGoal",
  "Anytime Goal Scorer": "Marcatore",
  "First Goal Scorer": "Primo Marcatore",
  "Last Goal Scorer": "Ultimo Marcatore",
  "Player Assists": "Assist",
  "Yes": "Si",
  "No": "No",
  "Highest Scoring Half": "Miglior Tempo per Goals",
  "1st Half": "1° Tempo",
  "2nd Half": "2° Tempo",
  "Home": "1",
  "Away": "2",
  "Draw": "X",
  "Odd": "Dispari",
  "Even": "Pari",
  "Odd/Even - First Half": "Pari / Dispari - 1° Tempo",
  "Odd/Even - Second Half": "Pari / Dispari - 2° Tempo",
  "Home Odd/Even": "Pari / Dispari - Casa",
  "Away Odd/Even": "Pari / Dispari - Ospite",
  "Home Team Exact Goals Number": "Somma Goals - Casa",
  "Away Team Exact Goals Number": "Somma Goals - Ospite",
  "Second Half Exact Goals Number": "Somma Goals - 2° Tempo",
  "more 3": "3+",
  "Home/Yes": "1 / SI",
  "Away/Yes": "2 / SI",
  "Draw/Yes": "X / SI",
  "Home/No": "1 / NO",
  "Away/No": "2 / NO",
  "Draw/No": "X / NO",
  "Draw/Home": "X / 1",
  "1 by 1": "1 - 1 Goal",
  "1 by 2": "1 - 2 Goals",
  "1 by 3": "1 - 3 Goals",
  "1 by 4+": "1 - 4+ Goals",
  "Score Draw": "Uguali Goals",
  "2 by 1": "2 - 1 Goal",
  "2 by 2": "2 - 2 Goals",
  "2 by 3": "2 - 3 Goals",
  "2 by 4+": "2 - 4+ Goals",
  "Winning Margin": "Scarto Vittoria",
  "Total Goals/Both Teams To Score": "Over-Under / Goal Goal",
  "o/yes 2.5": "OVER 2.5 / SI",
  "o/no 2.5": "OVER 2.5 / NO",
  "u/yes 2.5": "UNDER 2.5 / SI",
  "u/no 2.5": "UNDER 2.5 / NO",
  "Home/Over 2.5": "1 / OVER 2.5",
  "Away/Over 2.5": "2 / OVER 2.5",
  "Draw/Over 2.5": "X / OVER 2.5",
  "Home/Under 2.5": "1 / UNDER 2.5",
  "Away/Under 2.5": "2 / UNDER 2.5",
  "Draw/Under 2.5": "X / UNDER 2.5",
  "more 7": "7+",
  "Home +0": "1 -0",
  "Away +0": "2 -0",
  "Home -0.25": "1 -0.25",
  "Home +0.25": "1 +0.25",
  "Away -0.25": "2 -0.25",
  "Away +0.25": "2 +0.25",
  "Home -0.5": "1 -0.5",
  "Home +0.5": "1 +0.5",
  "Away -0.5": "2 -0.5",
  "Away +0.5": "2 +0.5",
  "Home -0.75": "1 -0.75",
  "Home +0.75": "1 +0.75",
  "Away -0.75": "2 -0.75",
  "Away +0.75": "2 +0.75",
  "Home -1": "1 -1",
  "Home +1": "1 +1",
  "Away -1": "2 -1",
  "Away +1": "2 +1",
  "Home -1.25": "1 -1.25",
  "Home +1.25": "1 +1.25",
  "Away -1.25": "2 -1.25",
  "Away +1.25": "2 +1.25",
  "Home -1.5": "1 -1.5",
  "Home +1.5": "1 +1.5",
  "Away -1.5": "2 -1.5",
  "Away +1.5": "2 +1.5",
  "Home -1.75": "1 -1.75",
  "Home +1.75": "1 +1.75",
  "Away -1.75": "2 -1.75",
  "Away +1.75": "2 +1.75",
  "Home -2": "1 -2",
  "Home +2": "1 +2",
  "Away -2": "2 -2",
  "Away +2": "2 +2",
  "Home -3": "1 -3",
  "Home +3": "1 +3",
  "Away -3": "2 -3",
  "Away +3": "2 +3",
  "Draw -1": "X -1",
  "Draw -2": "X -2",
  "Draw -3": "X -3",
  "Draw +1": "X +1",
  "Draw +2": "X +2",
  "Draw +3": "X +3",
};

const translationsOdds: Record<string, Record<string, string>> = {
  "Double Chance": {
    "Home/Draw": "1X",
    "Draw/Away": "X2",
    "Home/Away": "12",
  },
  "HT/FT Double": {
    "Home/Draw": "1 / X",
    "Draw/Away": "X / 2",
    "Home/Away": "1 / 2",
    "Draw/Draw": "X / X",
    "Home/Home": "1 / 1",
    "Away/Away": "2 / 2",
    "Away/Home": "2 / 1",
    "Away/Draw": "2 / X",
  }
}


export function translate(text: string): string {
  return translations[text] ?? text;
}

export function translateOdds(text: string, type: string): string {
  return translationsOdds[type]?.[text] ?? null;
}